In [41]:
import sys
import os
from functools import reduce
sys.path.append('../')
os.getcwd()

import numpy as np
from src.DecisionTree import DecisionTree
from src.utils import *
from src.validation import *

#from src.load_data import *


%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [42]:
#Load data
data_clean = np.loadtxt('../data/wifi_db/clean_dataset.txt')
x_data = data_clean[:,:-1]
y_data = data_clean[:,-1]
data_clean

array([[-64., -56., -61., ..., -82., -81.,   1.],
       [-68., -57., -61., ..., -85., -85.,   1.],
       [-63., -60., -60., ..., -85., -84.,   1.],
       ...,
       [-62., -59., -46., ..., -87., -88.,   4.],
       [-62., -58., -52., ..., -90., -85.,   4.],
       [-59., -50., -45., ..., -88., -87.,   4.]])

In [31]:
data = get_data('noisy_dataset.txt')
train = data[:1600,:]
val = data[1600:1800]
test = data[1800:,:]

In [33]:
train_depr = train[(train[:,-1] == 1) | (train[:,-1] == 2)]

In [34]:
decisiontree = DecisionTree()
tree = decisiontree.buildTree(train_depr)

In [38]:
decisiontree.prune(train_depr,val)

In [39]:
decisiontree.visualize()

Depth of the tree: 2

signal:3 val:-52.5
├─ leaf val:1.0
└─ leaf val:2.0


In [36]:
test

array([[-52., -56., -52., ..., -86., -84.,   3.],
       [-35., -55., -52., ..., -69., -82.,   2.],
       [-59., -56., -53., ..., -85., -84.,   4.],
       ...,
       [-15., -60., -59., ..., -74., -73.,   2.],
       [-52., -61., -48., ..., -80., -80.,   4.],
       [-50., -54., -60., ..., -76., -77.,   2.]])

In [19]:
test_depr = test
test_depr[0,-1] = 5

In [40]:
decisiontree.evaluate(test)

{'confusionmatrix': array([[46.,  2., 20., 50.],
        [ 2., 50., 29.,  1.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]),
 'precision': array([0.38983051, 0.6097561 , 0.        , 0.        ]),
 'recall': array([0.95833333, 0.96153846, 0.        , 0.        ]),
 'F1score': array([0.55421687, 0.74626866, 0.        , 0.        ]),
 'posClassRate': 0.48}

In [3]:
np.unique(y_data)

array([1., 2., 3., 4.])

In [10]:
folds = np.delete(np.arange(10),3)
print(folds)
for i in folds:
    print(i)

[0 1 2 4 5 6 7 8 9]
0
1
2
4
5
6
7
8
9


In [4]:
tree = DecisionTree()
tree.buildTree(data_clean)

({'attribute': 0,
  'val': -54.0,
  'lbranch': {'attribute': 4,
   'val': -59.0,
   'lbranch': {'attribute': 3,
    'val': -55.0,
    'lbranch': {'attribute': 2,
     'val': -55.0,
     'lbranch': {'attribute': 'leaf',
      'val': 1.0,
      'lbranch': None,
      'rbranch': None},
     'rbranch': {'attribute': 6,
      'val': -85.0,
      'lbranch': {'attribute': 4,
       'val': -62.0,
       'lbranch': {'attribute': 5,
        'val': -85.0,
        'lbranch': {'attribute': 0,
         'val': -56.0,
         'lbranch': {'attribute': 'leaf',
          'val': 4.0,
          'lbranch': None,
          'rbranch': None},
         'rbranch': {'attribute': 'leaf',
          'val': 3.0,
          'lbranch': None,
          'rbranch': None}},
        'rbranch': {'attribute': 'leaf',
         'val': 1.0,
         'lbranch': None,
         'rbranch': None}},
       'rbranch': {'attribute': 'leaf',
        'val': 4.0,
        'lbranch': None,
        'rbranch': None}},
      'rbranch': {'attrib

In [7]:
tree.evaluate(xtest,ytest)

NameError: name 'xtest' is not defined

In [5]:
tree.visualize()

signal:0 val:-54.0
├─ signal:4 val:-59.0
|  ├─ signal:3 val:-55.0
|  |  ├─ signal:2 val:-55.0
|  |  |  ├─ leaf val:1.0
|  |  |  └─ signal:6 val:-85.0
|  |  |     ├─ signal:4 val:-62.0
|  |  |     |  ├─ signal:5 val:-85.0
|  |  |     |  |  ├─ signal:0 val:-56.0
|  |  |     |  |  |  ├─ leaf val:4.0
|  |  |     |  |  |  └─ leaf val:3.0
|  |  |     |  |  └─ leaf val:1.0
|  |  |     |  └─ leaf val:4.0
|  |  |     └─ leaf val:1.0
|  |  └─ signal:1 val:-50.0
|  |     ├─ leaf val:3.0
|  |     └─ signal:0 val:-58.0
|  |        ├─ leaf val:3.0
|  |        └─ leaf val:1.0
|  └─ signal:4 val:-56.0
|     ├─ signal:3 val:-58.0
|     |  ├─ leaf val:4.0
|     |  └─ leaf val:3.0
|     └─ leaf val:4.0
└─ signal:0 val:-44.0
   ├─ signal:4 val:-70.0
   |  ├─ signal:3 val:-48.0
   |  |  ├─ signal:2 val:-57.0
   |  |  |  ├─ signal:0 val:-50.0
   |  |  |  |  ├─ leaf val:3.0
   |  |  |  |  └─ leaf val:2.0
   |  |  |  └─ leaf val:3.0
   |  |  └─ signal:1 val:-58.0
   |  |     ├─ signal:1 val:-59.0
   |  |     

In [111]:
data_clean = np.loadtxt('../data/wifi_db/clean_dataset.txt')

In [2]:
data_noisy = np.loadtxt('../data/wifi_db/noisy_dataset.txt')
data_noisy

array([[-59., -53., -51., ..., -79., -87.,   4.],
       [-66., -53., -59., ..., -81., -79.,   1.],
       [-41., -57., -63., ..., -66., -65.,   2.],
       ...,
       [-57., -54., -56., ..., -79., -82.,   1.],
       [-56., -52., -50., ..., -85., -88.,   3.],
       [-46., -54., -47., ..., -80., -73.,   3.]])

In [3]:
#result = cross_val(data_noisy,10)

In [4]:
#tree.buildTree(data_noisy)

In [5]:
train = data_noisy[:1800,:]
test = data_noisy[1800:,:]

In [6]:
decisiontree = DecisionTree()
tree = decisiontree.buildTree(train)
#decisiontree.visualize()

In [7]:
xtest = test[:,:-1]
ytest = test[:,-1]

In [8]:
decisiontree.evaluate(xtest,ytest)

{'confusionmatrix': array([[38.,  4.,  5.,  2.],
        [ 6., 42.,  3.,  2.],
        [ 2.,  3., 34.,  4.],
        [ 6.,  7.,  4., 38.]]),
 'precision': array([0.7755102 , 0.79245283, 0.79069767, 0.69090909]),
 'recall': array([0.73076923, 0.75      , 0.73913043, 0.82608696]),
 'F1score': array([0.75247525, 0.7706422 , 0.76404494, 0.75247525]),
 'posClassRate': 0.76}

In [21]:
decisiontree.prune(train,test)

In [22]:
decisiontree.evaluate(xtest,ytest)

{'confusionmatrix': array([[44.,  1.,  2.,  3.],
        [ 3., 47.,  4.,  1.],
        [ 3.,  2., 39.,  2.],
        [ 2.,  6.,  1., 40.]]),
 'precision': array([0.88      , 0.85454545, 0.84782609, 0.81632653]),
 'recall': array([0.84615385, 0.83928571, 0.84782609, 0.86956522]),
 'F1score': array([0.8627451 , 0.84684685, 0.84782609, 0.84210526]),
 'posClassRate': 0.85}

In [23]:
decisiontree.depth

15

In [24]:
decisiontree.statistics['confusionmatrix']

array([[44.,  1.,  2.,  3.],
       [ 3., 47.,  4.,  1.],
       [ 3.,  2., 39.,  2.],
       [ 2.,  6.,  1., 40.]])

In [297]:
#decisiontree.visualize()

signal:0 val:-54.0
├─ signal:4 val:-58.0
|  ├─ signal:3 val:-57.0
|  |  ├─ signal:1 val:-53.0
|  |  |  ├─ signal:2 val:-51.0
|  |  |  |  ├─ signal:5 val:-78.0
|  |  |  |  |  ├─ signal:1 val:-54.0
|  |  |  |  |  |  ├─ signal:6 val:-86.0
|  |  |  |  |  |  |  ├─ signal:4 val:-76.0
|  |  |  |  |  |  |  |  ├─ leaf val:1.0
|  |  |  |  |  |  |  |  └─ signal:4 val:-70.0
|  |  |  |  |  |  |  |     ├─ signal:2 val:-61.0
|  |  |  |  |  |  |  |     |  ├─ signal:4 val:-73.0
|  |  |  |  |  |  |  |     |  |  ├─ signal:0 val:-71.0
|  |  |  |  |  |  |  |     |  |  |  ├─ leaf val:4.0
|  |  |  |  |  |  |  |     |  |  |  └─ leaf val:1.0
|  |  |  |  |  |  |  |     |  |  └─ leaf val:1.0
|  |  |  |  |  |  |  |     |  └─ leaf val:1.0
|  |  |  |  |  |  |  |     └─ signal:6 val:-87.0
|  |  |  |  |  |  |  |        ├─ leaf val:1.0
|  |  |  |  |  |  |  |        └─ leaf val:1.0
|  |  |  |  |  |  |  └─ signal:6 val:-82.0
|  |  |  |  |  |  |     ├─ signal:4 val:-68.0
|  |  |  |  |  |  |     |  ├─ signal:1 val:-57.0
|

In [1]:
##Exploring Error

In [2]:
data_clean = np.loadtxt('../data/wifi_db/clean_dataset.txt')

In [3]:
splits = crossValidation_split(data_clean,10)

In [11]:
mask = np.ones(data_clean.shape[0], dtype=bool)
mask[splits[4]] = False
train = data_clean[mask,:]
test = data_clean[splits[4],:]

In [12]:
test

array([[-41., -58., -60., ..., -82., -74.,   2.],
       [-53., -59., -51., ..., -78., -77.,   3.],
       [-60., -57., -60., ..., -82., -80.,   1.],
       ...,
       [-42., -54., -51., ..., -70., -65.,   2.],
       [-49., -53., -55., ..., -81., -93.,   3.],
       [-63., -56., -61., ..., -83., -87.,   1.]])

In [13]:
test[:,-1]

array([2., 3., 1., 1., 4., 2., 1., 4., 2., 2., 4., 1., 3., 1., 4., 3., 4.,
       4., 3., 3., 4., 2., 4., 2., 2., 1., 4., 3., 1., 2., 3., 1., 2., 2.,
       2., 2., 1., 3., 1., 3., 2., 2., 4., 2., 2., 2., 1., 4., 3., 1., 3.,
       2., 2., 2., 2., 3., 4., 2., 1., 4., 2., 1., 1., 3., 4., 1., 1., 4.,
       1., 4., 2., 3., 4., 3., 1., 2., 1., 1., 2., 3., 4., 3., 4., 3., 2.,
       4., 2., 3., 2., 1., 4., 3., 2., 1., 2., 3., 2., 3., 2., 1., 2., 3.,
       4., 1., 1., 4., 4., 1., 3., 3., 3., 4., 3., 3., 1., 2., 1., 3., 4.,
       4., 4., 3., 2., 2., 1., 4., 2., 2., 2., 4., 3., 4., 3., 4., 1., 1.,
       1., 3., 1., 3., 4., 3., 2., 3., 3., 4., 4., 4., 2., 4., 3., 1., 3.,
       1., 4., 3., 4., 1., 1., 4., 1., 2., 3., 1., 3., 4., 2., 2., 1., 2.,
       2., 4., 1., 2., 4., 2., 1., 4., 4., 3., 2., 1., 4., 2., 1., 2., 2.,
       4., 3., 1., 1., 4., 1., 3., 4., 1., 4., 2., 3., 1.])

In [14]:
decisiontree = DecisionTree()
tree = decisiontree.buildTree(train)

In [15]:
        xtest = test[:,:-1]
        ytest = test[:,-1]

In [16]:
decisiontree.evaluate(xtest,ytest)

{'confusionmatrix': array([[50.,  0.,  0.,  1.],
        [ 0., 53.,  2.,  0.],
        [ 0.,  1., 44.,  0.],
        [ 0.,  0.,  0., 49.]]),
 'precision': array([0.98039216, 0.96363636, 0.97777778, 1.        ]),
 'recall': array([1.        , 0.98148148, 0.95652174, 0.98      ]),
 'F1score': array([0.99009901, 0.97247706, 0.96703297, 0.98989899]),
 'posClassRate': 0.98}

In [17]:
decisiontree.prune(train,test)

../src/DecisionTree.py:167: RuntimeWarning: invalid value encountered in true_divide
  precision = np.divide(np.diag(self.confusionmatrix),np.sum(self.confusionmatrix,axis = 1))


In [18]:
data = get_data('clean_dataset.txt')
data = data[data[:,-1] != 3]

In [19]:
data

array([[-63., -59., -61., ..., -90., -82.,   1.],
       [-60., -59., -51., ..., -88., -88.,   4.],
       [-63., -58., -65., ..., -81., -88.,   1.],
       ...,
       [-59., -51., -54., ..., -87., -88.,   4.],
       [-39., -53., -51., ..., -72., -70.,   2.],
       [-19., -59., -67., ..., -66., -74.,   2.]])

In [45]:
 small = load_testdata("clean_dataset_small.txt")

In [48]:
tree = DecisionTree(small)
tree.visualize()

Depth of the tree: 5

signal:2 val:-52.0
├─ signal:0 val:-43.0
|  ├─ signal:2 val:-54.0
|  |  ├─ signal:0 val:-44.0
|  |  |  ├─ leaf val:1.0
|  |  |  └─ leaf val:2.0
|  |  └─ leaf val:3.0
|  └─ leaf val:2.0
└─ leaf val:3.0


In [49]:
tree.tree

{'attribute': 2,
 'val': -52.0,
 'lbranch': {'attribute': 0,
  'val': -43.0,
  'lbranch': {'attribute': 2,
   'val': -54.0,
   'lbranch': {'attribute': 0,
    'val': -44.0,
    'lbranch': {'attribute': 'leaf',
     'val': 1.0,
     'lbranch': None,
     'rbranch': None},
    'rbranch': {'attribute': 'leaf',
     'val': 2.0,
     'lbranch': None,
     'rbranch': None}},
   'rbranch': {'attribute': 'leaf',
    'val': 3.0,
    'lbranch': None,
    'rbranch': None}},
  'rbranch': {'attribute': 'leaf',
   'val': 2.0,
   'lbranch': None,
   'rbranch': None}},
 'rbranch': {'attribute': 'leaf',
  'val': 3.0,
  'lbranch': None,
  'rbranch': None}}